name: Deploy site

on:
  push:
    branches:
      - src

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.81.0'
          extended: true

      - name: Build
        run: hugo --source src

      - name: Copy README
        run: cp README.md src/public/README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/public
          publish_branch: master
          cname: reservoircode.net
