name: Deploy site

on:
  push:
    branches:
      - src

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # pour le thème Hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.81.0'  # votre version actuelle

      - name: Build
        run: hugo --source src  # si vos sources sont dans /src

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/public
          publish_branch: master
          cname: reservoircode.net
